### PR TITLE
Hon game UI ux fixes/adding . in message post voting

### LINKED ISSUE #371: Messaging post voting - add a '.'
Task - Grammar edits in the result pending messaging.
Message shown once coins are staked - "You staked %x tokens on %y. Result is pending."
Currently '.' is missing.

Design:
Image

### PR DESCRIPTION
**Pull request by veer-asbytes**
fixes #371

### CODE REVIEW

**Comment by Natasha-GB** [comment]
Verified for both Hot/Not options chosen. Good to go. @veer-asbytes

**Comment by veer-asbytes** [comment]
@harshitasrivastav28 could you please review the changes?

**Comment by harshitasrivastav28** [comment]
Good to go @veer-asbytes

**Comment by harshitasrivastav28** [comment]
@rupansh This PR is good to go from product perspective. Please evaluate from code perspective.

**Review by rupansh-gob — APPROVED** [review]

**Pull request merged**
