### PR TITLE
Add profile icon and move leaderboard icon in hamburger menu #348

### LINKED ISSUE #348: Add the profile icon in bottom nav bar

### PR DESCRIPTION
**Pull request by veer-asbytes**
fixes #348

### CODE REVIEW

**Comment by veer-asbytes** [comment]
@komal-rs i made this pr on the latest changed of upstream main,
then why is it having deploy prev build fail?

**Comment by komal-rs** [comment]
@veer-asbytes Can you create a branch in the same repo and create another PR and check ?

**Comment by veer-asbytes** [comment]
> @veer-asbytes Can you create a branch in the same repo instead of in your github and create another PR and check ?

ok

**Comment by veer-asbytes** [comment]
https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/actions/runs/10595471894/job/29361688970?pr=362#step:6:30

**Pull request closed without merging**
