### PR TITLE
Share button in wallet page

### PR DESCRIPTION
**Pull request by veer-asbytes**
need some more optimisation

### CODE REVIEW

**Comment by harshitasrivastav28** [comment]
@ravibazz Please help in reviewing this PR. I have verified the flows. We will keep iterating above the flows to make it more seamless.

For now the sharing of profile link is working fine

**Comment by ravibazz** [comment]
There are merge conflicts could you resolve them

**Comment by veer-asbytes** [comment]
> There are merge conflicts could you resolve them

This issue has already been completed by Prakash.

**Comment by veer-asbytes** [comment]
This issue has already been completed by Prakash.

**Pull request closed without merging**
