### PR TITLE
Update boards homepage

### LINKED ISSUE #453: UX improvements
- [ ]  Make the Tokens clickable and open Token details tab
- [ ] Make the "Create Token" CTA visually appealing
- [ ] Spacing between CTA
- [ ] Fix data hierarchy to make the listing look visually balanced
- [x] Bottom navigation bars clicks are incorrect 
- [x] Back navigation is incorrect and requires to be fixed
- [x] When opening Create Token open the input form instead of landing user to profile.
- [ ] When clicking on profile, Open "Token tab" in icpump.fun instead of opening the reels tabs.

### PR DESCRIPTION
**Pull request by harshbaz**
partially fixes #453

### CODE REVIEW

**Comment by harshbaz** [comment]
@rupansh I used the [stylers crate](https://github.com/abishekatp/stylers) mentioned in the [leptop docs](https://book.leptos.dev/interlude_styling.html) but I did not install it in this PR. Not sure if to just run cargo add into the root or not.

**Comment by rupansh-gob** [comment]
> @rupansh I used the [stylers crate](https://github.com/abishekatp/stylers) mentioned in the [leptop docs](https://book.leptos.dev/interlude_styling.html). I added it using cargo but it doesn't work because it isn't added into the build config. Can you take a look?

stylers support for ssr seems sketchy, you have to add the git repo as dependency

i suggest a custom animation in tailwind instead for now https://tailwindcss.com/docs/animation#customizing-your-theme

**Comment by rupansh-gob** [comment]
Code changes look good
@harshitasrivastav28 please review the UI

**Comment by harshitasrivastav28** [comment]
UI changes look good! Lets that this live @harshbaz

**Review by rupansh-gob — APPROVED** [review]

**Pull request merged**
