### PR TITLE
Fix search style

### PR DESCRIPTION
**Pull request by harsh-yral**

### CODE REVIEW

**Comment by harshbaz** [comment]
@komal-sai-yral submitting the form does not initiate search. can you please take a look?

**Comment by harshbaz** [comment]
@komal-sai-yral ?

**Comment by komal-sai-yral** [comment]
@harshbaz we don't need these changes anymore since we are overhauling the search UI. We might still need the form thing figured out, but lets do that in the new UI

**Comment by harshbaz** [comment]
It'll be some time before those changes are finalized. And there's nothing new here except some markup and css changes. Please take a look at the form action and we can get this merged

**Comment by komal-sai-yral** [comment]
let's discuss in today's meet.

**Pull request closed without merging**
